DROP DATABASE IF EXISTS `train_schedule`;
-- MySQL Script generated by MySQL Workbench
-- 12/03/18 23:47:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema train_schedule
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema train_schedule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `train_schedule` DEFAULT CHARACTER SET utf8 ;
USE `train_schedule` ;

-- -----------------------------------------------------
-- Table `train_schedule`.`stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_schedule`.`stations` (
  `station_id` VARCHAR(2) NOT NULL,
  `station_name` VARCHAR(45) NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Information about all stations.';


-- -----------------------------------------------------
-- Table `train_schedule`.`trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_schedule`.`trains` (
  `train_id` VARCHAR(3) NOT NULL,
  `train_number` VARCHAR(6) NULL,
  `homestation_id` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`train_id`, `homestation_id`),
  INDEX `fk_train_station1_idx` (`homestation_id` ASC),
  CONSTRAINT `fk_train_station1`
    FOREIGN KEY (`homestation_id`)
    REFERENCES `train_schedule`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Information about all trains';


-- -----------------------------------------------------
-- Table `train_schedule`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_schedule`.`schedules` (
  `train_id` VARCHAR(3) NOT NULL,
  `current_station_id` VARCHAR(2) NOT NULL,
  `destinaton_station_id` VARCHAR(2) NOT NULL,
  `station_time` TIME NULL,
  PRIMARY KEY (`train_id`, `current_station_id`, `destinaton_station_id`),
  INDEX `fk_schedules_trains1_idx` (`train_id` ASC),
  INDEX `fk_schedules_stations1_idx` (`current_station_id` ASC),
  INDEX `fk_schedules_stations2_idx` (`destinaton_station_id` ASC),
  CONSTRAINT `fk_schedules_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `train_schedule`.`trains` (`train_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedules_stations1`
    FOREIGN KEY (`current_station_id`)
    REFERENCES `train_schedule`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedules_stations2`
    FOREIGN KEY (`destinaton_station_id`)
    REFERENCES `train_schedule`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Information about schedule.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;